title               : "Dapoer Ela 85"
description         : ""
baseurl             : "/toko/"
keywords            : ""
url                 : "https://dapoerela85.github.io/toko/"
locale              : "id-ID"
github_username     : dapoerela85
permalink           : pretty
markdown            : kramdown
paginate            : 1
paginate_path       : "/:num/"

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: "_posts/**"
      type: posts
    values:
      layout: post
      permalink: /:title/
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page
